version: '3.8'

services:
  backend:
    build: ./backend/
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    container_name: django-jwt-authentication
    
  fronted:
    build: ./frontend/
    volumes:
      - ./frontend/:/frontend
    ports:
      - 3000:5000
    container_name: django-jwt-authentication-frontend
    depends_on:
      - backend
    environment:
      - PORT=5000
    command: npm start